fix: deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -118,12 +118,39 @@ jobs:
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
             set -e
-            cd /var/www/front-craft
+            cd /var/www/front-craft || { echo "Directory /var/www/front-craft does not exist"; exit 1; }
             df -h
             ls -la
-            rm -rf .next public node_modules package.json package-lock.json || true
-            tar -xzf build.tar.gz
+            if [ -f build.tar.gz ]; then
+              tar -xzf build.tar.gz
+              rm -f build.tar.gz
+            else
+              echo "Error: build.tar.gz not found"
+              exit 1
+            fi
             ls -la
-            pm2 delete front-craft || true
-            pm2 start npm --name front-craft -- run start
-            pm2 save
+            if [ -d .next ] && [ -d public ] && [ -d node_modules ]; then
+              # Перемещаем содержимое public в корень
+              mv public/* .
+              mv public/.* . 2>/dev/null || true # Обрабатываем скрытые файлы, игнорируя ошибки, если их нет
+              rmdir public || true # Удаляем пустую папку public, игнорируя ошибку, если она уже удалена
+              chown -R ${REMOTE_USER}:${REMOTE_USER} .next node_modules
+              chmod -R 755 .next node_modules
+              pm2 kill
+              pm2 start "PORT=3000 HOST=0.0.0.0 npm run start" --name front-craft --cwd /var/www/front-craft
+              pm2 save
+            else
+              echo "Error: Required directories (.next, public, node_modules) are missing"
+              exit 1
+            fi
+          # script: |
+          #   set -e
+          #   cd /var/www/front-craft
+          #   df -h
+          #   ls -la
+          #   rm -rf .next public node_modules package.json package-lock.json || true
+          #   tar -xzf build.tar.gz
+          #   ls -la
+          #   pm2 delete front-craft || true
+          #   pm2 start npm --name front-craft -- run start
+          #   pm2 save
